openapi: 3.0.3
info:
  title: Simple API
  description: A simple API example in OpenAPI 3.0 format.
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /items:
    get:
      summary: Get a list of items
      description: Returns a list of items.
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        '404':
          description: No items found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new item
      description: Creates a new item by providing a name.
      requestBody:
        description: Item details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewItem'
      responses:
        '201':
          description: Item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
          example: "1"
        name:
          type: string
          example: "Example Item"
        create_time:
          type: string
          format: date-time
          example: "2024-08-21T14:00:00Z"
    NewItem:
      type: object
      properties:
        name:
          type: string
          example: "New Item"
      required:
        - name
    Error:
      type: object
      properties:
        message:
          type: string
          example: "An error occurred"
